parameters:
    env(RABBITMQ_DSN): 'amqp://%env(RABBITMQ_USER)%:%env(RABBITMQ_PASSWORD)%@%env(RABBITMQ_HOST)%:%env(RABBITMQ_PORT)%/%2f?lazy=0&connection_timeout=10&read_write_timeout=10&heartbeat=5'

framework:
    messenger:
        transports:
            default:
                dsn: "%env(RABBITMQ_DSN)%"
                options:
                    exchange: { name: 'messenger-topic', type: topic }
                    queue: { name: 'default', routing_key: 'async.command' }
            mailchimp_sync:
                dsn: "%env(RABBITMQ_DSN)%"
                options:
                    exchange: { name: 'messenger-topic', type: topic }
                    queue: { name: 'mailchimp_sync', routing_key: 'mailchimp.sync' }
            mailchimp_campaign:
                dsn: "%env(RABBITMQ_DSN)%"
                options:
                    exchange: { name: 'messenger-topic', type: topic }
                    queue: { name: 'mailchimp_campaign', routing_key: 'mailchimp.campaign' }
        routing:
            App\Mailchimp\CampaignMessageInterface: mailchimp_campaign
            App\Mailchimp\SynchronizeMessageInterface: mailchimp_sync
            App\Messenger\Message\AsynchronousMessageInterface: default
