parameters:
    timeline_max_messages: 10

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tests\App\Test\Geocoder\DummyGeocoder: ~

    Geocoder\Geocoder: '@Tests\App\Test\Geocoder\DummyGeocoder'

    app.mailer.transactional_client:
        class: 'Tests\App\Test\Mailer\NullEmailClient'
        public: false

    app.mailer.campaign_client:
        class: 'Tests\App\Test\Mailer\NullEmailClient'
        public: false

    App\Recaptcha\RecaptchaApiClient:
        class: 'Tests\App\Test\Recaptcha\DummyRecaptchaApiClient'
        public: false

    Tests\App\Test\Algolia\DummySearchService:
        decorates: 'search.service'
        arguments: ['@Tests\App\Test\Algolia\DummySearchService.inner']

    data_collector.messenger:
        class: Symfony\Component\Messenger\DataCollector\MessengerDataCollector
        tags: [{ name: 'data_collector', id: messenger, template: profiler/messenger.html.twig }]

#    App\VotingPlatform\Election\ResultCalculator:
#        public: true
#
#    App\Content\MediaFactory:
#        public: true
#
#    App\Content\ClarificationFactory:
#        public: true
#
#    App\Committee\CommitteeFactory:
#        public: true
#
#    App\Committee\Feed\CommitteeFeedManager:
#        public: true

#    App\Newsletter\NewsletterSubscriptionFactory:
#        public: true
#
#    App\Content\ProposalFactory:
#        public: true

#    League\Flysystem\FilesystemInterface:
#        public: true
