imports:
    - { resource: services_dev.yaml }

parameters:
    timeline_max_messages: 10
    app_host: "test.%env(APP_HOST)%"
    amp_host: "test.%env(AMP_HOST)%"
    legislatives_host: "test.legislatives.%app_host%"
    ssl_encryption_key: "%env(SSL_ENCRYPTION_KEY)%"
    ssl_private_key: "%env(SSL_PRIVATE_KEY)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    app.map.google_maps_static_provider:
        class: 'Tests\App\Test\Map\DummyStaticMapProvider'

    app.glide.cache_adapter:
        class: 'League\Flysystem\Memory\MemoryAdapter'

    old_sound_rabbit_mq.mailer_campaign_producer:
        class: 'Tests\App\Test\Producer\MailerNullProducer'
        public: false

    old_sound_rabbit_mq.mailer_transactional_producer:
        class: 'Tests\App\Test\Producer\MailerNullProducer'
        public: false

    old_sound_rabbit_mq.deputy_message_dispatcher_producer:
        class: 'Tests\App\Test\Producer\DeputyMessageNullProducer'

    old_sound_rabbit_mq.chezvous_algolia_producer:
        class: 'Tests\App\Test\Producer\ChezVous\AlgoliaNullProducer'

    Tests\App\Consumer\DummyConsumer: ~

    Tests\App\Test\Payment\PayboxProvider:
        arguments:
            - '%env(SSL_PRIVATE_KEY)%'

    test.App\Adherent\Handler\RemoveAdherentAndRelatedDataCommandHandler:
        alias: App\Adherent\Handler\RemoveAdherentAndRelatedDataCommandHandler

    test.App\Vision\IdentityDocumentParser: '@App\Vision\IdentityDocumentParser'

    Tests\App\Image\DummyImageManager: ~

    App\Image\ImageManagerInterface: '@Tests\App\Image\DummyImageManager'

    App\Messenger\MessageRecorder\MessageRecorderInterface: '@App\Messenger\MessageRecorder\MessageRecorder'

    App\Committee\Feed\CommitteeFeedManager: ~

    League\Flysystem\FilesystemInterface: '@League\Flysystem\Filesystem'
